import React from "react";
import robotImg from "../../assets/img/keyword-robot.png";
// import robotImgKeyword from "../../assets/img/keyword-robot.png";
// import robotImgClue from "../../assets/img/clue-robot.png";
import { useNavigate } from "react-router-dom";
import { Link } from "react-router-dom";

const Home = () => {

  const navigate = useNavigate();

  const handleSubmit = (event) => {
  event.preventDefault()
  const keyword = event.target.keyword.value
  fetch(`http://crosswordcreate.xyz:52093/GenCrossword/${keyword}`)
    .then(res => res.json())
    .then(array => 
      navigate('/puzzle', {
        state: {
          query: keyword,
          results: array,
        }
      })
    )
  }

  return (
    <>
      <header className="header" id="header">
        <div className="container">
          <div className="header-box">
            <div className="header-text">
              <h3>Crossword Gen</h3>
              <h1>A crossword generator? <br></br><span>Enter your keyword now.</span></h1>
              <h4>
                Use our crossword generator to generate the crossword puzzle of
                your dreams. Words and clues will be provided to you.
              </h4>
            </div>
            <div className="header-form">
              <form onSubmit={handleSubmit}>
                <input type="hidden" name="form-name" value="header" />
                <div className="header-item">
                  <input
                    type="text"
                    name="keyword"
                    id=""
                    className="input"
                    placeholder="Enter a keyword"
                    required
                  />
                  <input
                    type="submit"
                    value="Make your puzzle!"
                    className="btn-submit"
                  />
                </div>
              </form>
            </div>
            <div className="header-image">
              <img src={robotImg} alt="Fiverr Reviews logogenius5" />
            </div>
          </div>
        </div>
      </header>
      {/* Detail Section */}
      <section className="detail">
        <div className="container">
          <div className="detail-box">
            <div className="detail-text">
              <h2><span>01.</span>Word Database</h2>
              <p>
                Utilizing the open-source <span><i>fast</i>Text library,</span> puzzle answers can
                be generated by finding words that are related to the provided keyword. 
              </p>
              <p>
                <i>fast</i>Text even works with <span>157</span> languages!
              </p>
              <div className="detail-button-box">
                <div className="detail-button">
                <Link class="btn-green" to="/About">More about us</Link>
                </div>
                <div className="detail-button">
                  <a href="https://fasttext.cc/" className="btn-transparent">
                    <i>fast</i>Text &#8594;
                  </a>
                </div>
              </div>
            </div>
            <div className="detail-image">
              <img src={robotImg} alt="" />
            </div>
          </div>
        </div>
      </section>

      {/* Detail 2 Section */}
      <section className="detail2">
        <div className="container">
          <div className="detail2-box">
            <div className="detail2-image">
              <img src={robotImg} alt="" />
            </div>
            <div className="detail2-text">
              <div className="detail2-text-header-box">
                <h2><span>02.</span>Clues Database</h2>
              </div>
              
              <p>
                We use the <span>cryptics.georgeho.org</span> dataset to get clues for your
                crossword puzzle. After generating the answers to your crossword,
                we search through this database to match each answer with a clue!
              </p>
              <p>
                This dataset includes over <span>half a million</span> clues collected over
                12 years!
              </p>
              <div className="detail2-button-box">
                <div className="detail2-button">
                <Link class="btn-green" to="/">Make a crossword</Link>
                </div>
                <div className="detail2-button">
                <Link class="btn-transparent" to="/Share">Share the word! &#8594;</Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default Home;
